name: Deploy to Coolify

on:
  push:
    branches:
      - migracion-postgres

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64, coolify]

    steps:
      - name: Trigger Coolify deployment
        run: |
          curl --fail \
            --request GET "${{ secrets.COOLIFY_WEBHOOK }}" \
            --header "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"
